name: Production

on:
  push:
    tags: [v*]

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          build-args: |
            NEXT_PUBLIC_STRAPI_API_URL=${{ vars.NEXT_PUBLIC_STRAPI_API_URL }}
            NEXT_PUBLIC_STORAGE_HOST=${{ vars.NEXT_PUBLIC_STORAGE_HOST }}
            NEXT_PUBLIC_SITE_NAME=${{ vars.NEXT_PUBLIC_SITE_NAME }}
            NEXT_PUBLIC_SITE_URL=${{ vars.NEXT_PUBLIC_SITE_URL }}
          platforms: linux/arm64,linux/amd64
          push: true
          tags: ghcr.io/${{github.repository}}:${{github.ref_name}},ghcr.io/${{github.repository}}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build
    uses: valuable-promo/infra/.github/workflows/deploy-production.yaml@main
    with:
      namespace: valuable-promo-prod
      yaml-path: k8s/prod.depl.yaml
    secrets:
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_PROD }}
