name: Staging

on:
  push:
    branches: [main]
    paths-ignore:
      - '**/**.md'
      - 'docker-compose.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: staging
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: |
            NEXT_PUBLIC_STRAPI_API_URL=$NEXT_PUBLIC_STRAPI_API_URL
            NEXT_PUBLIC_STORAGE_HOST=$NEXT_PUBLIC_STORAGE_HOST
          platforms: linux/arm64,linux/amd64
          push: true
          tags: ghcr.io/${{github.repository}}:main
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build
    uses: valuable-promo/infra/.github/workflows/deploy-staging.yaml@main
    with:
      namespace: valuable-promo-staging
      deployment: headless-depl
    secrets:
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_STAGING }}
