name: Staging

on:
  push:
    branches: [main]
    paths-ignore:
      - '**/**.md'
      - 'docker-compose.yml'
jobs:
  build:
    uses: valuable-promo/infra/.github/workflows/build-staging.yml@main
    with:
      username: ${{ github.actor }}
      build-args: |
        NEXT_PUBLIC_STRAPI_API_URL=${{ vars.NEXT_PUBLIC_STRAPI_API_URL }}
        NEXT_PUBLIC_STORAGE_HOST=${{ vars.NEXT_PUBLIC_STORAGE_HOST }}
    secrets:
      PASSWORD: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: build
    uses: valuable-promo/infra/.github/workflows/deploy-staging.yaml@main
    with:
      namespace: valuable-promo-staging
      deployment: frontend-depl
    secrets:
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_STAGING }}
