name: Staging

on:
  push:
    branches: [main]
    paths-ignore:
      - '**/**.md'
      - 'docker-compose.yml'
jobs:
  test:
    if: "!startsWith(github.ref, 'refs/tags/')" # Don't run on tags
    uses: ./.github/workflows/testing.yaml
  build:
    needs: test
    runs-on: ubuntu-latest
    environment:
      name: staging
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate image tag
        run: echo "IMAGE_TAG=$(echo $GITHUB_REF | sed 's|refs/heads/||')-$(echo $GITHUB_SHA | head -c 7)-$(date +%s)" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          build-args: |
            NEXT_PUBLIC_STRAPI_API_URL=${{ vars.NEXT_PUBLIC_STRAPI_API_URL }}
            NEXT_PUBLIC_STORAGE_HOST=${{ vars.NEXT_PUBLIC_STORAGE_HOST }}
            NEXT_PUBLIC_SITE_NAME=${{ vars.NEXT_PUBLIC_SITE_NAME }}
            NEXT_PUBLIC_SITE_URL=${{ vars.NEXT_PUBLIC_SITE_URL }}
            NEXT_PUBLIC_PAGE_SIZE=${{ vars.NEXT_PUBLIC_PAGE_SIZE }}
            NEXT_PUBLIC_CSE_ID=${{ vars.NEXT_PUBLIC_CSE_ID }}
            NEXT_PUBLIC_ARTICLE_ADS_SLOT=${{ vars.NEXT_PUBLIC_ARTICLE_ADS_SLOT }}
            NEXT_PUBLIC_CA_PUB=${{ vars.NEXT_PUBLIC_CA_PUB }}
          platforms: linux/arm64,linux/amd64
          push: true
          tags: ghcr.io/${{github.repository}}:${{env.IMAGE_TAG}}
          cache-from: type=gha
          cache-to: type=gha,mode=max
